version: '3.7'
services:
  mongodb_container:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      INIT_WAIT_SEC: ${INIT_WAIT_SEC}
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/init-scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
  init_script:
    image: alpine:3.14
    depends_on:
      - minio
    volumes:
      - ./scripts/init-scripts:/scripts
    command: /bin/sh -c "/scripts/init-bucket.sh"
    env_file:
      - .env
volumes:
  minio_storage: {}